---
title: "13.2.1"
author: "siyu"
date: "2023-02-24"
output: html_document
---

```{r}
library(tidyverse)
library(nycflights13)
flights
```

```{r}
flights2 <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier)
flights2
```

```{r}
flights2 %>%
  select(-origin, -dest)%>%
  left_join(airlines, by = "carrier")
```

```{r}
flights2 %>%
  select(-origin, -dest)%>%
  mutate(name=airlines$name[match(carrier, airlines$carrier)])
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3"
)

x%>%
  inner_join(y, by="key")

x2 <-x%>%
  left_join(y, by="key")
x2

x3 <-x%>%
  right_join(y, by="key")
x3

x4 <-x%>%
  full_join(y, by="key")
x4
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     1, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2"
)
left_join(x, y, by = "key")
```

```{r}
flights2%>%
  left_join(weather)
```

```{r}
flights2 %>% 
  left_join(airports, c("dest" = "faa"))
```

```{r}
flights2 %>% 
  left_join(airports, c("origin" = "faa"))
```

```{r}
airports %>%
  semi_join(flights, c("faa" = "dest")) %>%
  ggplot(aes(lon, lat)) +
    borders("state") +
    geom_point() +
    coord_quickmap()
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3"
)

x%>%
  semi_join(x,y, by="key")

y%>%
  anti_join(x,y, by="key")
```